name = "CordraClient"
uuid = "9b7dba48-593b-43c8-b146-7a84bfe01e50"
authors = ["Camilo Velez <cvelezra@mongtomerycollege.edu>"]
version = "0.1.0-dev"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
HTTP = "^0.9"
JSON = "^0.21"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
